"""
Experiment B: AttnEntropy-KV controller vs uniform / random / attention-mass /
MEDA-style baselines on Qwen2.5-VL + LongVideoBench.

Loads frozen calibration thresholds (from calibrate.py), evaluates 9 conditions
at matched ~3 average KV bits over the 200-eval split, writes per-sample JSONL +
summary table. Pareto plot is generated by expB_pareto_plot.py.

Conditions:
    B0 Uniform-INT4-KV (4 avg bits, Pareto anchor)
    B1 Uniform-INT2-KV (2 avg bits, Pareto anchor)
    B2 Random-mixed (avg ~3 bits, layer-level, 3 seeds)
    B3 Attention-mass token protection (top-p%->INT4, rest->INT2)
    B4 MEDA-style entropy: layer-level cache-eviction analogue (here: layer-level
       bit budget proportional to entropy mass; baseline meant to mimic MEDA's
       allocation philosophy in our precision-routing setting)
    B5 Oracle: per-layer logit-KL bit assignment (privileged)
    B6 AttnEntropy V1 (layer-level)
    B7 AttnEntropy V2 ((layer, KV-head)-level)
    B8 AttnEntropy V3 ((layer, token)-level via online attention-mass mask)
"""
from __future__ import annotations

import argparse
import json
import random
from collections import defaultdict
from pathlib import Path

import numpy as np
import torch

from attn_entropy_hook import entropy_hook
from data_longvideobench import (
    DEFAULT_SPLIT_FILE,
    filter_items,
    load_all_items,
    load_split,
)
from fake_quant_kv_cache import BitController, FakeQuantKVCache
from run_inference import load_model, run_condition, score_item


RESULTS_DIR = Path(__file__).resolve().parents[1] / "results"
CALIBRATION_DIR = Path(__file__).resolve().parents[1] / "calibration"


# ---------------- controller builders ----------------

def build_uniform(num_layers: int, num_kv_heads: int, k_bits: int, v_bits: int) -> BitController:
    c = BitController(num_layers, num_kv_heads, mode="V1")
    c.set_global(k_bits=k_bits, v_bits=v_bits)
    return c


def build_random_mixed(num_layers: int, num_kv_heads: int, target_avg: float, seed: int) -> BitController:
    c = BitController(num_layers, num_kv_heads, mode="V1")
    rng = random.Random(seed)
    levels = (2, 4)
    n_high = int(round(num_layers * (target_avg - 2) / 2.0))
    high_idx = set(rng.sample(range(num_layers), n_high))
    for i in range(num_layers):
        b = 4 if i in high_idx else 2
        c.set_layer(i, k_bits=b, v_bits=b)
    return c


def build_meda_style(num_layers: int, num_kv_heads: int, layer_entropy: list[float],
                     target_avg: float) -> BitController:
    """Allocate bits proportional to entropy mass — high-entropy layers get more bits."""
    c = BitController(num_layers, num_kv_heads, mode="V1")
    ent = torch.tensor(layer_entropy)
    # Map entropy quartiles to bits hitting target_avg
    levels = [2, 4, 8]
    sorted_ent, sorted_idx = ent.sort()
    bits_sorted = torch.full((num_layers,), levels[1], dtype=torch.long)
    n3 = num_layers // 3
    bits_sorted[:n3] = levels[0]
    bits_sorted[2 * n3:] = levels[2]
    bits = torch.zeros_like(bits_sorted)
    bits[sorted_idx] = bits_sorted
    for i in range(num_layers):
        c.set_layer(i, k_bits=int(bits[i]), v_bits=int(bits[i]))
    return c


def build_v1(num_layers: int, num_kv_heads: int, v1_bits: list[int]) -> BitController:
    c = BitController(num_layers, num_kv_heads, mode="V1")
    for i, b in enumerate(v1_bits):
        c.set_layer(i, k_bits=int(b), v_bits=int(b))
    return c


def build_v2(num_layers: int, num_kv_heads: int, v2_bits: list[list[int]]) -> BitController:
    c = BitController(num_layers, num_kv_heads, mode="V2")
    for i, row in enumerate(v2_bits):
        bits_t = torch.tensor(row, dtype=torch.long)
        c.set_layer(i, k_bits=bits_t, v_bits=bits_t)
    return c


def build_v3(num_layers: int, num_kv_heads: int,
             p_per_layer: list[float], hi: int, lo: int) -> BitController:
    """Skeleton V3 controller. The protected mask is per-example and set inside
    the per-item scoring loop (see _score_v3_item)."""
    c = BitController(num_layers, num_kv_heads, mode="V3", default_k_bits=lo, default_v_bits=lo)
    c.v3_p_per_layer = p_per_layer  # type: ignore[attr-defined]
    c.v3_hi = hi
    c.v3_lo = lo
    return c


# ---------------- avg-bits accounting ----------------

def avg_bits_v1(v1_bits: list[int]) -> float:
    return float(np.mean(v1_bits))


def avg_bits_v2(v2_bits: list[list[int]]) -> float:
    return float(np.mean([b for row in v2_bits for b in row]))


def avg_bits_v3(p_per_layer: list[float], hi: int, lo: int) -> float:
    p = float(np.mean(p_per_layer))
    return p * hi + (1 - p) * lo


# ---------------- main ----------------

def run(args):
    items = load_all_items()
    split = load_split(args.split_file)
    eval_items = filter_items(items, split["eval"])
    if args.limit:
        eval_items = eval_items[: args.limit]
    print(f"[expB] eval_items={len(eval_items)}")

    thresholds_path = (
        args.thresholds
        or CALIBRATION_DIR
        / f"thresholds_{args.model.split('/')[-1]}_avg{args.target_avg_bits:.1f}_frames{args.frames[0]}.json"
    )
    cal = json.loads(Path(thresholds_path).read_text())
    print(f"[expB] loaded thresholds from {thresholds_path}")

    model, processor = load_model(args.model, dtype="bfloat16", attn_impl="sdpa")
    num_layers = cal["num_layers"]
    num_kv_heads = cal["num_kv_heads"]

    out_jsonl = RESULTS_DIR / f"expB_rollouts_{args.model.split('/')[-1]}_avg{args.target_avg_bits:.1f}.jsonl"
    if out_jsonl.exists() and not args.append:
        out_jsonl.unlink()

    conditions: list[tuple[str, BitController, float, bool]] = []  # name, controller, avg_bits, needs_entropy_hook
    if "B0" in args.conditions:
        conditions.append(("B0_Uniform_INT4", build_uniform(num_layers, num_kv_heads, 4, 4), 4.0, False))
    if "B1" in args.conditions:
        conditions.append(("B1_Uniform_INT2", build_uniform(num_layers, num_kv_heads, 2, 2), 2.0, False))
    if "B2" in args.conditions:
        for s in args.random_seeds:
            conditions.append(
                (f"B2_Random_seed{s}",
                 build_random_mixed(num_layers, num_kv_heads, args.target_avg_bits, seed=s),
                 args.target_avg_bits, False)
            )
    if "B3" in args.conditions:
        # Attention-mass: V3 with protected mask = top-p% by attention. p chosen
        # uniform across layers to hit target avg.
        p = (args.target_avg_bits - 2.0) / 2.0
        c = build_v3(num_layers, num_kv_heads, [p] * num_layers, hi=4, lo=2)
        c.expB_v3_mode = "attention_mass"  # type: ignore[attr-defined]
        conditions.append(("B3_AttnMass", c, args.target_avg_bits, True))
    if "B4" in args.conditions:
        c = build_meda_style(num_layers, num_kv_heads, cal["layer_entropy"], args.target_avg_bits)
        conditions.append(("B4_MEDA_style", c, args.target_avg_bits, False))
    if "B6" in args.conditions:
        c = build_v1(num_layers, num_kv_heads, cal["v1_bits_per_layer"])
        conditions.append(("B6_AttnEnt_V1", c, avg_bits_v1(cal["v1_bits_per_layer"]), False))
    if "B7" in args.conditions:
        c = build_v2(num_layers, num_kv_heads, cal["v2_bits_per_layer_kvhead"])
        conditions.append(("B7_AttnEnt_V2", c, avg_bits_v2(cal["v2_bits_per_layer_kvhead"]), False))
    if "B8" in args.conditions:
        c = build_v3(num_layers, num_kv_heads,
                     cal["v3_protected_fraction_per_layer"],
                     hi=cal["v3_hi_bits"], lo=cal["v3_lo_bits"])
        c.expB_v3_mode = "attention_mass_per_layer"  # type: ignore[attr-defined]
        conditions.append(("B8_AttnEnt_V3", c,
                           avg_bits_v3(cal["v3_protected_fraction_per_layer"],
                                       cal["v3_hi_bits"], cal["v3_lo_bits"]),
                           True))

    for n_frames in args.frames:
        for name, controller, avg_bits, needs_hook in conditions:
            print(f"[expB] {name} frames={n_frames} avg_bits={avg_bits:.2f}")
            hook_factory = entropy_hook if needs_hook else None
            run_condition(
                model, processor, eval_items, n_frames=n_frames,
                controller=controller, condition=f"{name}_frames{n_frames}",
                model_id=args.model, out_jsonl=out_jsonl, avg_kv_bits=avg_bits,
                entropy_hook_factory=hook_factory,
            )

    summarize(out_jsonl)


# ---------------- summary ----------------

def _bootstrap_ci(arr, n_boot=2000, seed=0):
    arr = np.asarray(arr, dtype=np.float32)
    if arr.size == 0:
        return float("nan"), float("nan"), float("nan")
    rng = np.random.default_rng(seed)
    means = [arr[rng.integers(0, arr.size, arr.size)].mean() for _ in range(n_boot)]
    return float(arr.mean()), float(np.percentile(means, 2.5)), float(np.percentile(means, 97.5))


def summarize(jsonl_path: Path) -> None:
    rows = [json.loads(line) for line in jsonl_path.read_text().splitlines() if line.strip()]
    by_cond = defaultdict(list)
    for r in rows:
        by_cond[r["condition"]].append(r)

    # Recovery vs uniform: among items where the matched-frame uniform-INT2 condition is wrong,
    # what fraction does this method get right?
    uniform_int2 = {
        (r["item_id"], r["n_frames"]): r["is_correct"]
        for cond, rs in by_cond.items() if "Uniform_INT2" in cond
        for r in rs
    }

    out = ["# Experiment B — AttnEntropy KV controller\n"]
    out.append("| Condition | n | acc | 95% CI | avg KV bits | per-bucket acc | recovery vs INT2 |")
    out.append("|---|---:|---:|---|---:|---|---:|")
    for cond, rs in sorted(by_cond.items()):
        accs = [r["is_correct"] for r in rs]
        mean, lo, hi = _bootstrap_ci(accs)
        avg_bits = next((r["avg_kv_bits"] for r in rs if r.get("avg_kv_bits") is not None), float("nan"))
        bucket_acc = {}
        for b in ("short", "mid", "long", "very_long"):
            arr = [r["is_correct"] for r in rs if r["duration_bucket"] == b]
            bucket_acc[b] = (sum(arr) / len(arr)) if arr else float("nan")
        bucket_str = " / ".join(f"{b}:{bucket_acc[b]:.2f}" for b in ("short", "mid", "long", "very_long"))
        if "Uniform_INT2" not in cond:
            target = [r for r in rs if uniform_int2.get((r["item_id"], r["n_frames"])) is False]
            recovery = sum(int(r["is_correct"]) for r in target) / max(1, len(target))
        else:
            recovery = float("nan")
        out.append(f"| {cond} | {len(rs)} | {mean:.3f} | [{lo:.3f}, {hi:.3f}] | {avg_bits:.2f} | {bucket_str} | {recovery:.3f} |")

    summary_path = jsonl_path.with_name(jsonl_path.stem.replace("rollouts", "summary") + ".md")
    summary_path.write_text("\n".join(out) + "\n")
    print(f"[expB] summary -> {summary_path}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default="Qwen/Qwen2.5-VL-7B-Instruct")
    ap.add_argument("--frames", type=int, nargs="+", default=[64, 128])
    ap.add_argument("--target_avg_bits", type=float, default=3.0)
    ap.add_argument("--thresholds", type=Path, default=None)
    ap.add_argument("--limit", type=int, default=0)
    ap.add_argument("--append", action="store_true")
    ap.add_argument("--random_seeds", type=int, nargs="+", default=[0, 1, 2])
    ap.add_argument("--conditions", nargs="+",
                    default=["B0", "B1", "B2", "B3", "B4", "B6", "B7", "B8"])
    ap.add_argument("--split_file", type=Path, default=DEFAULT_SPLIT_FILE)
    args = ap.parse_args()
    run(args)


if __name__ == "__main__":
    main()
