#!/usr/bin/env python3
"""
ExpD Phase B: log per-cycle W4 action chunks for the LIBERO-PRO Object x0.2
trial set, so the trial-gate analysis can compute action-derived signals that
attention-only Phase A couldn't (chunk variance, within-chunk sign flips,
inter-chunk discrepancy).

For each of 50 matched-pair trials at libero_object_temp x0.2:
  - Set ctrl to W4 base (vision tower + language_model.layers.0 protected at FP16,
    expert always FP16 — same protection map as Phase A diagnostic).
  - Run a W4-Floor rollout with SeededInferContext (matched-pair noise per cycle).
  - At each inference cycle, the action_callback logs the full 10x7 action chunk.

Output: results/expD_chunks__<out-tag>.jsonl
   one record per cycle: {suite, task_id, seed, episode_idx, cycle_idx, env_step, chunk}

Trials are generated by `pro_full_trials()` from expB_sis_validation, so the
(suite, task_id, seed, episode_idx) tuples match the existing V3 diagnostic
exactly — chunk records can be joined to attention features by trial-key
(per-trial summary stats only; the per-cycle joins are not necessary for
trial-gate features).

~15 min on H100. Skips SIS perturbations + FP16 forwards (only deployable
W4-side signals are required for B/C/D as defined in the Phase B plan).
"""

import argparse
import os
import sys
import time
from pathlib import Path

import numpy as np

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
if SCRIPT_DIR not in sys.path:
    sys.path.insert(0, SCRIPT_DIR)

import json
import utils
import rollout as rollout_mod
from sis_utils import PrecisionController
from expB_sis_validation import pro_full_trials, SeededInferContext


def trials_from_rollouts(rollouts_path: Path) -> list:
    """Extract the unique (suite, task_id, seed, episode_idx) trial set from
    an existing rollouts JSONL. Use this to keep the chunk run aligned with
    a previously-completed experiment regardless of which seed formula
    `pro_full_trials` happens to use at the moment."""
    seen = []
    seen_set = set()
    with open(rollouts_path) as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            r = json.loads(line)
            key = (r["suite"], int(r["task_id"]), int(r["seed"]), int(r["episode_idx"]))
            if key not in seen_set:
                seen_set.add(key)
                seen.append(key)
    return seen


def run_chunk_logging_trial(policy, model, ctrl, suite, task_id, seed, episode_idx, out_path):
    """Run a single W4 rollout for (suite, task_id, seed, ep) and log per-cycle
    action chunks to `out_path`. Returns the rollout record."""
    rollout_key = {
        "suite": suite, "task_id": int(task_id),
        "seed": int(seed), "episode_idx": int(episode_idx),
    }
    cycle_idx_box = [-1]
    chunks_buffer = []

    def action_cb(env_step, action_chunk):
        cycle_idx_box[0] += 1
        chunks_buffer.append({
            **rollout_key,
            "cycle_idx": cycle_idx_box[0],
            "env_step": int(env_step),
            "chunk": np.asarray(action_chunk, dtype=np.float32).tolist(),
        })

    seeded = SeededInferContext(policy, model, base_seed=seed)
    with seeded:
        ctrl.use_bits(4)
        rec = rollout_mod.run_rollout(
            policy,
            task_id=task_id, suite=suite,
            seed=seed, episode_idx=episode_idx,
            pre_infer_callback=lambda t: ctrl.use_bits(4),
            action_callback=action_cb,
            verbose=False,
        )

    # Append all chunks at end (single file open per trial).
    for c in chunks_buffer:
        utils.append_jsonl(c, out_path)
    return rec


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--pro-config", default="Object:x:0.2")
    p.add_argument("--pro-n-per-suite", type=int, default=50)
    p.add_argument("--out-tag", default="libero_pro_obj_x0.2")
    p.add_argument("--match-rollouts", default=None,
                   help="path to an existing expB_w4__<tag>_rollouts.jsonl. When set, "
                        "the trial set is read from that file (ignoring --pro-n-per-suite) "
                        "so chunks join cleanly with prior outcomes regardless of any "
                        "seed-formula changes in pro_full_trials.")
    args = p.parse_args()

    utils.setup_logging()

    pro_cfg = rollout_mod.parse_pro_config_str(args.pro_config)
    rollout_mod.set_libero_pro_config(pro_cfg)
    utils.log(f"[expD-chunks] LIBERO-PRO config: {pro_cfg}")

    if args.match_rollouts:
        rollouts_path = Path(args.match_rollouts)
        trials = trials_from_rollouts(rollouts_path)
        utils.log(f"[expD-chunks] matched {len(trials)} trials from {rollouts_path.name}")
    else:
        trials = pro_full_trials(pro_cfg, n_per_suite=args.pro_n_per_suite)
        utils.log(f"[expD-chunks] {len(trials)} trials from pro_full_trials")

    out_path = Path(utils.RESULTS_DIR) / f"expD_chunks__{args.out_tag}.jsonl"
    if out_path.exists():
        utils.log(f"[expD-chunks] removing existing {out_path}")
        out_path.unlink()

    utils.log("[expD-chunks] loading policy + ctrl...")
    policy, model = utils.load_policy()
    ctrl = PrecisionController(model, bits_list=(4,), group_size=128)

    n_succ = 0
    try:
        for i, (suite, task_id, seed, ep) in enumerate(trials):
            t0 = time.time()
            try:
                rec = run_chunk_logging_trial(
                    policy, model, ctrl, suite, task_id, seed, ep, out_path,
                )
                if rec.success:
                    n_succ += 1
                utils.log(
                    f"[expD-chunks] {i+1}/{len(trials)} {suite} task={task_id} "
                    f"seed={seed} ep={ep} success={rec.success} steps={rec.steps} "
                    f"wall={time.time()-t0:.1f}s | running_succ={n_succ}/{i+1}"
                )
            except Exception as e:
                utils.log(f"[expD-chunks] FAILED trial {(suite, task_id, seed, ep)}: {e}")
                import traceback
                traceback.print_exc()
    finally:
        ctrl.use_fp16()

    utils.log(f"[expD-chunks] DONE; {n_succ}/{len(trials)} W4 successes; chunks at {out_path}")


if __name__ == "__main__":
    main()
